### ISSUE TITLE
margin of .o-grid gets overridden on <figure>

### ISSUE THREAD

**Issue by nelhop** [lnolte/und-css#16]
Not sure if this is really a bug or more an enhancement...

The margin of `.o-grid` gets overridden by the "user agent stylesheet" (from Chrome) when it is a `<figure>`

![Bildschirmfoto 2020-09-25 um 12 52 56](https://user-images.githubusercontent.com/1862955/94259319-91ec9180-ff2e-11ea-8586-5a50f46e96ea.png)

**Comment by lnolte** [comment]
Seems like a more aggressive reset stylesheet should do the trick. I'll consider it

**Comment by lnolte** [comment]
I just checked with the history. The initial pre-release of `und-css` used `normalize.css` as a reset, which does not reset `figure` styles. The issue you mentioned is probably using a prerelease version.

Since the "official" (read "versioned") releases of `und-css` `minireset.css` is used, which is a more aggressive reset stylesheet. Updating the version should fix this.
