### ISSUE TITLE
calculations with variables in MS-Edge

### ISSUE THREAD

**Issue by nelhop** [lnolte/und-css#17]
Microsoft Edge is not able to calculate values with a css-variable.

In Example: `calc(var(--o-grid--spacing) / 2)` on `.o-grid>*` does not resolve.

![Bildschirmfoto 2020-09-30 um 10 06 35](https://user-images.githubusercontent.com/1862955/94659633-e1530900-0304-11eb-9be7-a20643751874.png)

**Comment by lnolte** [comment]
For reference: According to Can I Use MS Edge should have full Custom Properties support (https://caniuse.com/css-variables).

According to this related issues of another CSS Framework (https://github.com/fortrabbit/teutonic-css/issues/2) the issue might be fixed by explicitly writing `padding-top`, `padding-left`, etc. Sounds to me like this is something that might be handled in the build process using a postcss plugin like this one https://www.npmjs.com/package/postcss-shorthand-expand.

However, as this should not be an issue in the Chromium based Edge versions anymore this feels like something that shouldn't be fixed within the framework but rather in the build process of projects that need to be served to older versions of Microsoft Browsers.
